import { AppDefinition, FIELDS } from "../utils/index";

export const Customer_Master: AppDefinition = {
  appName: "01. 取引先マスタ（得意先・仕入先）",
  appId: 6,
  space: "営業スペース",
  fields: {
    businessPartnerCode: {
      label: "取引先コード",
      hiraganaLabel: "とりひきさきコード",
      fieldCode: "取引先コード",
      type: FIELDS.string,
    },
    parentCompany: {
      label: "親会社/グループ会社",
      hiraganaLabel: "おやがいしゃ / ぐるーぷ がいしゃ",
      fieldCode: "親会社_グループ会社",
      type: FIELDS.string,
    },
    businessPartnerName: {
      label: "取引先名",
      hiraganaLabel: "とりひきさきなま",
      fieldCode: "取引先名",
      type: FIELDS.string,
      required: true,
    },
    shortName: {
      label: "略名",
      hiraganaLabel: "りゃくめい",
      fieldCode: "略名",
      type: FIELDS.string,
      required: true,
    },
    registrationNumber: {
      label: "登録番号",
      hiraganaLabel: "とうろくばんごう",
      fieldCode: "登録番号",
      type: FIELDS.string,
    },
    parentCompanyPostalCode: {
      label: "郵便番号(親会社)",
      hiraganaLabel: "ゆうびんばんごう (おやがいしゃ)",
      fieldCode: "郵便番号_親会社_",
      type: FIELDS.string,
      section:
        "  住所/連絡先 その他  (じゅうしょ / れんらくさき そのた) Address / Contact information / Others",
    },
    parentCompanyAddress: {
      label: "住所(親会社)",
      hiraganaLabel: "じゅうしょ (おやがいしゃ)",
      fieldCode: "住所_親会社_",
      type: FIELDS.string,
      section:
        "  住所/連絡先 その他  (じゅうしょ / れんらくさき そのた) Address / Contact information / Others",
    },
    parentCompanyPhone: {
      label: "TEL(親会社)",
      hiraganaLabel: "TEL (おやがいしゃ)",
      fieldCode: "TEL_親会社_",
      type: FIELDS.link,
      section:
        "  住所/連絡先 その他  (じゅうしょ / れんらくさき そのた) Address / Contact information / Others",
    },
    parentCompanyFax: {
      label: "FAX(親会社)",
      hiraganaLabel: "FAX (おやがいしゃ)",
      fieldCode: "FAX_親会社_",
      type: FIELDS.link,
      section:
        "  住所/連絡先 その他  (じゅうしょ / れんらくさき そのた) Address / Contact information / Others",
    },
    clientPostalCode: {
      label: "郵便番号(得意先)",
      hiraganaLabel: "ゆうびんばんごう (とくいさき)",
      fieldCode: "郵便番号_得意先_",
      type: FIELDS.string,
      required: true,
      section:
        "  住所/連絡先 その他  (じゅうしょ / れんらくさき そのた) Address / Contact information / Others",
    },
    clientAddress: {
      label: "住所(得意先)",
      hiraganaLabel: "じゅうしょ (とくいさき)",
      fieldCode: "住所_得意先_",
      type: FIELDS.string,
      required: true,
      section:
        "  住所/連絡先 その他  (じゅうしょ / れんらくさき そのた) Address / Contact information / Others",
    },
    clientPhone: {
      label: "TEL(得意先)",
      hiraganaLabel: "TEL (とくいさき)",
      fieldCode: "TEL_得意先_",
      type: FIELDS.string,
      required: true,
      section:
        "  住所/連絡先 その他  (じゅうしょ / れんらくさき そのた) Address / Contact information / Others",
    },
    clientFax: {
      label: "FAX(得意先)",
      hiraganaLabel: "FAX (とくいさき)",
      fieldCode: "FAX_得意先_",
      type: FIELDS.string,
      section:
        "  住所/連絡先 その他  (じゅうしょ / れんらくさき そのた) Address / Contact information / Others",
    },
    supplierAddressSame: {
      label: "仕入先住所も同様",
      hiraganaLabel: "しいれさきじゅうしょもどうよう",
      fieldCode: "仕入先住所も同様",
      type: FIELDS.checkbox,
      options: ["同様"],
      section:
        "  住所/連絡先 その他  (じゅうしょ / れんらくさき そのた) Address / Contact information / Others",
    },
    businessPartnerCategory: {
      label: "取引先カテゴリ",
      hiraganaLabel: "とりひきさきカテゴリ",
      fieldCode: "取引先カテゴリ",
      type: FIELDS.checkbox,
      options: ["取引先", "仕入先", "その他"],
      section:
        "  住所/連絡先 その他  (じゅうしょ / れんらくさき そのた) Address / Contact information / Others",
    },
    contractAttachmentClient: {
      label: "契約書等添付(得意先用）",
      hiraganaLabel: "けいやくしょとうてんぷ (とくいさきよう)",
      fieldCode: "契約書等添付",
      type: FIELDS.file,
      section:
        "  住所/連絡先 その他  (じゅうしょ / れんらくさき そのた) Address / Contact information / Others",
    },
    contractAttachmentSupplier: {
      label: "契約書等添付(仕入用）",
      hiraganaLabel: "けいやくしょとうてんぷ (しにゅうよう)",
      fieldCode: "契約書等添付_0",
      type: FIELDS.file,
      section:
        "  住所/連絡先 その他  (じゅうしょ / れんらくさき そのた) Address / Contact information / Others",
    },
    clientStatus: {
      label: "得意先ステータス",
      hiraganaLabel: "とくいさきすてーたす",
      fieldCode: "得意先ステータス",
      type: FIELDS.string,
      group: "基本情報  (きほんじょうほう) Basic information",
    },
    clientClassification: {
      label: "得意先分類区分",
      hiraganaLabel: "とくいさきぶんるいくぶ",
      fieldCode: "得意先分類区分",
      type: FIELDS.dropdown,
      options: [
        "DNP",
        "凸版印刷",
        "民間印刷会社",
        "民間その他",
        "公共機関入札",
        "ネット販売",
        "直需販売",
        "その他売上",
      ],
      group: "基本情報  (きほんじょうほう) Basic information",
    },
    oldClientCode: {
      label: "旧得意先コード",
      hiraganaLabel: "きゅうとくいさきこーど",
      fieldCode: "旧得意先コード",
      type: FIELDS.string,
      group: "基本情報  (きほんじょうほう) Basic information",
    },
    groupName: {
      label: "グループ名",
      hiraganaLabel: "ぐるーぷめい",
      fieldCode: "グループ名",
      type: FIELDS.dropdown,
      options: [
        "（１）大日本印刷関連",
        "（２）凸版印刷関連",
        "（３）民間印刷会社",
        "（４）民間その他",
        "（５）公共機関入札",
        "（６）ネット販売",
        "（７）直需販売",
        "（８）その他売上",
      ],
      group: "基本情報  (きほんじょうほう) Basic information",
    },
    category: {
      label: "分類",
      hiraganaLabel: "ぶんるい",
      fieldCode: "分類",
      type: FIELDS.dropdown,
      options: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "DNP",
        "凸版",
        "アド印刷",
        "ヤマガタ",
        "タガヤ",
        "麗都商事",
        "大阪商工信金",
        "西日本住宅",
        "東日本住宅",
      ],
      group: "基本情報  (きほんじょうほう) Basic information",
    },
    invoiceRecipient: {
      label: "請求書送付先",
      hiraganaLabel: "せいきゅうしょそうふさき",
      fieldCode: "請求書送付先",
      type: FIELDS.radio,
      options: ["親会社", "得意先名"],
      required: true,
      group: "基本情報  (きほんじょうほう) Basic information",
    },
    deliveryNoteRecipient: {
      label: "納品書送付先",
      hiraganaLabel: "のひんしょそうふさき",
      fieldCode: "納品書送付先",
      type: FIELDS.radio,
      options: ["親会社", "得意先名"],
      required: true,
      group: "基本情報  (きほんじょうほう) Basic information",
    },
    personInCharge: {
      label: "担当者",
      hiraganaLabel: "たんとうしゃ",
      fieldCode: "担当者",
      type: FIELDS.string,
      group: "基本情報  (きほんじょうほう) Basic information",
    },
    internalPersonInCharge: {
      label: "自社担当者",
      hiraganaLabel: "じしゃたんとうしゃ",
      fieldCode: "自社担当者",
      type: FIELDS.userSelect,
      group: "基本情報  (きほんじょうほう) Basic information",
    },
    personInChargeNotes: {
      label: "担当者についてのメモ",
      hiraganaLabel: "たんとうしゃについてのめも",
      fieldCode: "担当者についてのメモ",
      type: FIELDS.textArea,
      group: "基本情報  (きほんじょうほう) Basic information",
    },
    consumptionTaxCategory: {
      label: "消費税区分",
      hiraganaLabel: "しょうひぜいくぶん",
      fieldCode: "消費税区分",
      type: FIELDS.dropdown,
      options: ["外", "内", "無"],
      group: "基本情報  (きほんじょうほう) Basic information",
    },
    fractionRoundingCategory: {
      label: "端数区分",
      hiraganaLabel: "はすうくぶん",
      fieldCode: "端数区分",
      type: FIELDS.dropdown,
      options: ["四捨五入", "切上", "切捨"],
      group: "基本情報  (きほんじょうほう) Basic information",
    },
    calculationCategory: {
      label: "計算区分",
      hiraganaLabel: "けいさんくぶん",
      fieldCode: "計算区分",
      type: FIELDS.dropdown,
      options: ["明細", "伝票", "請求"],
      group: "基本情報  (きほんじょうほう) Basic information",
    },
    invoiceClosingDate: {
      label: "請求締日",
      hiraganaLabel: "せいきゅうし゛しりび",
      fieldCode: "請求締日",
      type: FIELDS.dropdown,
      options: ["5日", "10日", "15日", "20日", "25日", "末日", "随時請求"],
      group: "基本情報  (きほんじょうほう) Basic information",
    },
    invoiceIssuanceCategory: {
      label: "請求書発行区分",
      hiraganaLabel: "せいきゅうしょはっこうくぶん",
      fieldCode: "請求書発行区分",
      type: FIELDS.dropdown,
      options: [
        "郵送",
        "担当渡",
        "電子指定アプリ",
        "メール",
        "(無)指定請求書",
        "無",
      ],
      group: "基本情報  (きほんじょうほう) Basic information",
    },
    deliveryNoteIssuanceCategory: {
      label: "納品書発行区分",
      hiraganaLabel: "のひんしょはっこうくぶん",
      fieldCode: "納品書発行区分",
      type: FIELDS.dropdown,
      options: [
        "郵送",
        "担当渡",
        "電子指定アプリ",
        "メール",
        "(無)指定納品書",
        "無",
      ],
      group: "基本情報  (きほんじょうほう) Basic information",
    },
    electronicInvoicing: {
      label: "電子請求",
      hiraganaLabel: "でんしせいきゅう",
      fieldCode: "電子請求",
      type: FIELDS.checkbox,
      options: ["✓"],
      group: "基本情報  (きほんじょうほう) Basic information",
    },
    collectionScheduleCategory: {
      label: "回収予定区分",
      hiraganaLabel: "かいしゅうよていくぶん",
      fieldCode: "回収予定区分",
      type: FIELDS.dropdown,
      options: ["当月", "翌月", "翌々月"],
      group: "基本情報  (きほんじょうほう) Basic information",
    },
    plannedCollectionDate: {
      label: "回収予定日",
      hiraganaLabel: "かいしゅうよていび",
      fieldCode: "回収予定日",
      type: FIELDS.dropdown,
      options: [
        "1日",
        "2日",
        "3日",
        "4日",
        "5日",
        "6日",
        "7日",
        "8日",
        "9日",
        "10日",
        "11日",
        "12日",
        "13日",
        "14日",
        "15日",
        "16日",
        "17日",
        "18日",
        "19日",
        "20日",
        "21日",
        "22日",
        "23日",
        "24日",
        "25日",
        "26日",
        "27日",
        "28日",
        "29日",
        "30日",
        "31日",
        "末日",
        "随時請求",
      ],
      group: "基本情報  (きほんじょうほう) Basic information",
    },
    collectionCategory: {
      label: "回収区分",
      hiraganaLabel: "かいしゅうくぶん",
      fieldCode: "回収区分",
      type: FIELDS.checkbox,
      options: ["手形"],
      group: "基本情報  (きほんじょうほう) Basic information",
    },
    amountInTenThousandYenUnits: {
      label: "金額(以上の金額)万",
      hiraganaLabel: "きんがく (いじょうのきんがく) まん",
      fieldCode: "金額_以上の金額_",
      type: FIELDS.number,
      group: "基本情報  (きほんじょうほう) Basic information",
    },

    paymentTermDays: {
      label: "サイト",
      hiraganaLabel: "サイト",
      fieldCode: "サイト",
      type: FIELDS.number,
      group: "取引条件  (とりひきじょうけん) Transaction terms",
    },
    notes: {
      label: "備考",
      hiraganaLabel: "びこう",
      fieldCode: "備考",
      type: FIELDS.textArea,
      group: "基本情報  (きほんじょうほう) Basic information",
    },
    purchaseCategory: {
      label: "仕入カテゴリ",
      hiraganaLabel: "しりょうかてごり",
      fieldCode: "仕入カテゴリ",
      type: FIELDS.dropdown,
      options: [
        "01.商品仕入",
        "02.商品仕入(否インボス)",
        "03.材料仕入",
        "04.材料仕入(否インボス)",
        "05.外注加工",
        "06.外注加工(否インボス)",
        "07.原修繕費",
        "08.原修繕費(否インボス)",
        "09.原消耗品",
        "10.原消耗品(否インボス)",
        "11.原包装費",
        "12.原包装費(否インボス)",
        "13.原運送代",
        "14.原運送代(否インボス)",
        "15.原雑費",
        "16.原雑費(否インボス)",
        "17.消耗品",
        "18.消耗品(否インボス)",
        "19.修繕費",
        "20.修繕費(否インボス)",
        "21.事務消耗品",
        "22.事務消耗品(否インボス)",
        "23.運送代",
        "24.配送",
        "25.配送(否インボス)",
        "26.雑費",
        "27.雑費(否インボス)",
        "28.包装費",
        "29.包装費(否インボス)",
        "30.経費",
        "31.経費(否インボス)",
        "32.雑雑費",
        "33.雑原修繕費",
        "34.雑修繕費",
        "35.雑原消耗品",
        "36.雑消耗品",
        "37.雑材料仕入",
        "38.雑商品仕入",
        "39.雑運送費",
        "40.雑外注",
        "41.雑経費",
      ],
      group: "仕入先情報	(しいれさきじょうほう)	Supplier information",
    },
    consumptionTaxCategorySupplier: {
      label: "消費税区分(仕入先)",
      hiraganaLabel: "しょうひぜいくぶん (しいれさき)",
      fieldCode: "消費税区分_仕入先_",
      type: FIELDS.dropdown,
      options: ["外", "内", "無"],
      group: "仕入先情報	(しいれさきじょうほう)	Supplier information",
    },
    fractionRoundingCategorySupplier: {
      label: "端数区分(仕入先)",
      hiraganaLabel: "はすうくぶん (しいれさき)",
      fieldCode: "端数区分_仕入先_",
      type: FIELDS.dropdown,
      options: ["四捨五入", "切上", "切捨"],
      group: "仕入先情報	(しいれさきじょうほう)	Supplier information",
    },
    calculationCategorySupplier: {
      label: "計算区分(仕入先)",
      hiraganaLabel: "けいさんくぶん (しいれさき)",
      fieldCode: "計算区分_仕入先_",
      type: FIELDS.dropdown,
      options: ["明細", "伝票", "請求"],
      group: "仕入先情報	(しいれさきじょうほう)	Supplier information",
    },
    supplierPersonInCharge: {
      label: "担当者",
      hiraganaLabel: "たんとうしゃ",
      fieldCode: "担当者_0",
      type: FIELDS.string,
      group: "仕入先情報	(しいれさきじょうほう)	Supplier information",
    },
    postalCodeSupplier: {
      label: "郵便番号(仕入先)",
      hiraganaLabel: "ゆうびんばんごう (しいれさき)",
      fieldCode: "郵便番号_仕入先_",
      type: FIELDS.string,
      group: "仕入先情報	(しいれさきじょうほう)	Supplier information",
    },
    addressSupplier: {
      label: "住所(仕入先)",
      hiraganaLabel: "じゅうしょ (しいれさき)",
      fieldCode: "住所_仕入先_",
      type: FIELDS.string,
      group: "仕入先情報	(しいれさきじょうほう)	Supplier information",
    },
    supplierPhone: {
      label: "TEL(仕入先)",
      hiraganaLabel: "てれほん (しいれさき)",
      fieldCode: "TEL_仕入先_",
      type: FIELDS.link,
      group: "仕入先情報	(しいれさきじょうほう)	Supplier information",
    },
    supplierFax: {
      label: "FAX(仕入先)",
      hiraganaLabel: "ふぁくす (しいれさき)",
      fieldCode: "FAX_仕入先_",
      type: FIELDS.link,
      group: "仕入先情報	(しいれさきじょうほう)	Supplier information",
    },
    supplierNotes: {
      label: "備考",
      hiraganaLabel: "びこう",
      fieldCode: "備考_0",
      type: FIELDS.textArea,
      group: "仕入先情報	(しいれさきじょうほう)	Supplier information",
    },

    quotationHistory: {
      label: "見積履歴",
      hiraganaLabel: "みつもりりれき",
      fieldCode: "見積履歴_0",
      type: FIELDS.recordList,
      relatedApp: "09. 見積書管理",
      displayConditions: [
        {
          thisAppField: "得意先ID",
          destAppField: "得意先ID",
          condition: "equal",
        },
      ],
      displayFields: [
        "見積日付",
        "見積書番号",
        "担当者",
        "品名",
        "サイズ",
        "紙",
        "印刷",
        "窓",
        "口糊",
        "見積額(税抜)",
      ],
    },
    deliveryHistory: {
      label: "納品履歴",
      hiraganaLabel: "のうひんりれき",
      fieldCode: "納品履歴_0",
      type: FIELDS.recordList,
      relatedApp: "10. 納品書管理(売上)",
      displayConditions: [
        {
          thisAppField: "得意先ID",
          destAppField: "得意先ID",
          condition: "equal",
        },
      ],
      displayFields: [
        "納品書番号",
        "売上日付",
        "担当者",
        "納品日",
        "納品金額合計(税抜)",
      ],
    },
    invoiceHistory: {
      label: "請求履歴",
      hiraganaLabel: "せいきゅうりれき",
      fieldCode: "請求履歴_0",
      type: FIELDS.recordList,
      relatedApp: "11. 請求書管理(売上)",
      displayConditions: [
        {
          thisAppField: "得意先ID",
          destAppField: "得意先ID",
          condition: "equal",
        },
      ],
      displayFields: [
        "請求日付",
        "請求書番号",
        "担当者",
        "今回御買上額(税抜)",
        "合計御買上金額",
      ],
    },
    prefectureParentCompany: {
      label: "都道府県(親会社)",
      hiraganaLabel: "とどうふけん (おやがいしゃ)",
      fieldCode: "都道府県_親会社_",
      type: FIELDS.string,
      isDeveloperField: true,
    },
    cityParentCompany: {
      label: "市区町村(親会社)",
      hiraganaLabel: "しくちょうそん (おやがいしゃ)",
      fieldCode: "市区町村_親会社_",
      type: FIELDS.string,
      isDeveloperField: true,
    },
    streetParentCompany: {
      label: "町名(親会社)",
      hiraganaLabel: "まちめい (おやがいしゃ)",
      fieldCode: "町名_親会社_",
      type: FIELDS.string,
      isDeveloperField: true,
    },
    prefectureClient: {
      label: "都道府県(得意先)",
      hiraganaLabel: "とどうふけん (とくいさき)",
      fieldCode: "都道府県_得意先_",
      type: FIELDS.string,
      isDeveloperField: true,
    },
    cityClient: {
      label: "市区町村(得意先)",
      hiraganaLabel: "しくちょうそん (とくいさき)",
      fieldCode: "市区町村_得意先_",
      type: FIELDS.string,
      isDeveloperField: true,
    },
    streetClient: {
      label: "町名(得意先)",
      hiraganaLabel: "まちめい (とくいさき)",
      fieldCode: "町名_得意先_",
      type: FIELDS.string,
      isDeveloperField: true,
    },
    prefectureSupplier: {
      label: "都道府県(仕入先)",
      hiraganaLabel: "とどうふけん (しいれさき)",
      fieldCode: "都道府県_仕入先_",
      type: FIELDS.string,
      isDeveloperField: true,
    },
    citySupplier: {
      label: "市区町村(仕入先)",
      hiraganaLabel: "しくちょうそん (しいれさき)",
      fieldCode: "市区町村_仕入先_",
      type: FIELDS.string,
      isDeveloperField: true,
    },
    streetSupplier: {
      label: "町名(仕入先)",
      hiraganaLabel: "まちめい (しいれさき)",
      fieldCode: "町名_仕入先_",
      type: FIELDS.string,
      isDeveloperField: true,
    },
    mfBusinessPartnerId: {
      label: "MF取引先ID",
      hiraganaLabel: "えむえふとりひきさきID",
      fieldCode: "MF取引先ID",
      type: FIELDS.string,
      isDeveloperField: true,
    },
    previousPaymentBalance: {
      label: "前回支払残高",
      hiraganaLabel: "ぜんかいしはらいざんだか",
      fieldCode: "前回支払残高",
      type: FIELDS.number,
      isDeveloperField: true,
    },
    previousAccountsPayableBalance: {
      label: "前回買掛残高",
      hiraganaLabel: "ぜんかいかいかけざんだか",
      fieldCode: "前回買掛残高",
      type: FIELDS.number,
      isDeveloperField: true,
    },
    oldClientCodeSupplier: {
      label: "旧得意先コード(仕入)",
      hiraganaLabel: "きゅうとくいさきこーど (しいれ)",
      fieldCode: "旧得意先コード_仕入_",
      type: FIELDS.string,
      isDeveloperField: true,
    },
    flag: {
      label: "フラグ",
      hiraganaLabel: "フラグ",
      fieldCode: "フラグ",
      type: FIELDS.string,
      isDeveloperField: true,
    },
    clientId: {
      label: "得意先ID",
      hiraganaLabel: "とくいさきID",
      fieldCode: "得意先ID",
      type: FIELDS.recordNumber,
    },
  },
} as const;
